### PR TITLE
admin feature added

### PR DESCRIPTION
**Pull request by Subham142**
1) admin can fetch all the users
2)admin can fetch a particular user by its Id

Closes: #204 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

### CODE REVIEW

**Comment by Subham142** [comment]
@Namanl2001  please review it

**Comment by Subham142** [comment]
@Namanl2001  please approve this so i can work on different admin features

**Review by Namanl2001 — APPROVED** [review]
lgtm

**Comment by Subham142** [comment]
Will you merge this ..or should I continue here

**Comment by Subham142** [comment]
@Namanl2001 really sorry for poking again...I thought the updating backend ( adding routes and controllers) were a level 3...after this..merge I won't be needing to add extra routes or controllers..

**Pull request merged**
