### PR TITLE
Header Improvement

### PR DESCRIPTION
**Pull request by deeptea22**
## Related Issue 

- Header made sticky

Closes: #31 

### Describe the changes you've made

I have made the existing header sticky and fixed. This helps to view the header at all times.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
No unusual behaviour

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

## Additional Info (optional)
Let me know if there are any other changes to be made. Thank you :)

### CODE REVIEW

**Comment by Namanl2001** [comment]
image
image
Changes are not proper. If facing problem head to the discord project channel to discuss with mentors. Thanks

**Comment by Namanl2001** [comment]
@deeptea22 6 days no reaponse from your side should this issue be assigned to someone else?

**Comment by deeptea22** [comment]
okay

**Comment by Namanl2001** [comment]
@deeptea22 this issue is still open. do you want to take this up again? Thanks

**Comment by Namanl2001** [comment]
Closing due to no response

**Pull request closed without merging**
