### PR TITLE
new flip cards

### PR DESCRIPTION
**Pull request by ChitvanRamani22**
## Related Issue 

- Info about the related issue 

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] I have verified/tested my code by running it locally.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Review by sagar-barapatre — APPROVED** [review]
Screenshot 2021-04-07 at 8 47 31 PM
I have tested the changes and it's all working fine. Good work @ChitvanRamani22

**Comment by ChitvanRamani22** [comment]
@sagar-barapatre thanks a lot!

**Comment by ChitvanRamani22** [comment]
@Namanl2001 can you please review this pr.

**Comment by Namanl2001** [comment]
@ChitvanRamani22 remove commas between classes as is leading to (9, , , )
No need for "pin code:" just add it to the end of the address.
Move Contact no. below the book image on the card as for big descriptions/addresses it is creating the problem.

Make a new pr for these changes and labels (for scores) will be added to that only.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i have made the changes and have pushed them to the same branch.

**Pull request merged**
