### PR TITLE
added admin middleware

### PR DESCRIPTION
**Pull request by Subham142**
Closes: #196 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Enhancement in the existing features
- [ ] Other

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

### CODE REVIEW

**Comment by Subham142** [comment]
@Namanl2001  please review

**Comment by Namanl2001** [comment]
Looks good.
Are you planning to add the admin routes in future PR's? Or in this only?

**Comment by Subham142** [comment]
Of course I'll add the routes and controllers.....that's the reason I wanted the middleware to be merged...

I just wanted you to see how and what I'm planning

**Comment by Namanl2001** [comment]
Cool! Let's merge this then 👍

**Comment by Subham142** [comment]
I'm raising issue for the controller and routes 
Pleas assign it to me

**Comment by Subham142** [comment]
@Namanl2001 would really appreciate if you would change it to a level 2

I had to study the user shcema and backend to customize the admin according to this project

**Comment by Namanl2001** [comment]
> @Namanl2001 would really appreciate if you would change it to a level 2
> 
> I had to study the user shcema and backend to customize the admin according to this project

Sure, No problem

**Pull request merged**
