### PR TITLE
card alignment

### PR DESCRIPTION
**Pull request by ChitvanRamani22**
Screenshot (491)
Screenshot (492)
Screenshot (494)
Screenshot (495)

### CODE REVIEW

**Review by sagar-barapatre — APPROVED** [review]

**Comment by Namanl2001** [comment]
image
@ChitvanRamani22, as you can see the pin filter, is at the center but the name filter is not, for a specific resolution.

**Comment by Namanl2001** [comment]
@ChitvanRamani22 Any update on this?

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i cannot reslove this.
It fails at some or the other resolution.

**Comment by Namanl2001** [comment]
You can just try to follow the pin filter styling. May be

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i tried that and  other things too but it did not work.

**Comment by Namanl2001** [comment]
Okay, I'll try to resolve it and let you know.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 that would be great.
Thanks

**Review by Namanl2001 — CHANGES_REQUESTED** [review]
in `src/components/style.css` change L364 to `justify-content: center;` and L374 to ` margin-left: 12.5%;`
And see the magic. 😄

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i could not see anything related to alignment at lines 364 and 374.

**Review by Namanl2001 — APPROVED** [review]
Great! Thanks

**Pull request merged**
