### PR TITLE
Added config.example.js and instructions to run the server locally

### PR DESCRIPTION
**Pull request by singhayushh**
## Related Issue 

Closes: #86 

### Describe the changes you've made

I've updated the instructions to run the app locally in the readme.md file as well as added a `config.example.js` file in the backend directory for reference to other contributors as to how to set up their own config.js file.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [x] Other

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

### CODE REVIEW

**Comment by singhayushh** [comment]
Note: Additions were done in the PR #85 that's why commits for both issues are included in this PR. Merging this will merge #85 automatically.

**Comment by Namanl2001** [comment]
Added small changes. PHAL!

**Comment by singhayushh** [comment]
I saw in the code that you're using the same pass variable for mongo pass as well as email password. Not the safest thing to do 😅

**Review by Namanl2001 — APPROVED** [review]
Great work! will make passwords different. Thanks

**Pull request merged**
