### PR TITLE
Styled the Navbar

### PR DESCRIPTION
**Pull request by pi-squared-4**
## Related Issue 

- Info about the related issue 

Closes: #35 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] I have verified/tested my code by running it locally.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by sagar-barapatre** [comment]
Can you provide us with reference images or GIF's ?

**Comment by pi-squared-4** [comment]
I am sorry, reference images of my commit ?

**Comment by pi-squared-4** [comment]
image

Here it is.

**Comment by pi-squared-4** [comment]
@Namanl2001 Can you review?

**Comment by Namanl2001** [comment]
I guess only the font is changed. @guptaji6489 PHAL!

**Comment by pi-squared-4** [comment]
Changed the padding and space between. There is not much of the scroll space so cannot assign any stickiness to it. Can add animations to the brand name.

**Comment by Namanl2001** [comment]
@sagar-barapatre & @guptaji6489 please have a look here

**Comment by sagar-barapatre** [comment]
@pi-squared-4 you have added only CSS and removed all the structure of the code.

**Comment by pi-squared-4** [comment]
There were some unnecessary blocks and so I though, they were by mistake.

**Comment by Namanl2001** [comment]
@pi-squared-4 You have totally removed all the code from `navbar.jsx` what are you trying to do?

**Pull request closed without merging**
