### PR TITLE
Auto closable alert

### PR DESCRIPTION
**Pull request by nikitakapoor1919**
## Related Issue 

- Earlier alert was not auto closable

Closes: #58

### Describe the changes you've made

Added set interval feature on alert after which it closes automatically

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [X] My changes generate no new warnings.
- [X] I have verified/tested my code by running it locally.

## Additional Info (optional)
-

### CODE REVIEW

**Comment by Namanl2001** [comment]
Why are there changes in readme.md file? Please resolve them.
Also add gif to support your changes.

**Comment by nikitakapoor1919** [comment]
Alert closes after few seconds.
I have resolved conflicts with readme.
Please check.

**Comment by Namanl2001** [comment]
LGTM! but there are various unintentional changes PHAL [here](https://github.com/Namanl2001/MERN-Gurujii-dev/pull/61/files)

**Comment by Namanl2001** [comment]
If you are facing issues refer to https://github.com/Namanl2001/MERN-Gurujii-dev/blob/master/contributing.md

**Comment by nikitakapoor1919** [comment]
@Namanl2001  Sir I have copy paste same code of master branch but still there are changes . Should I delete readme ?
So that only other files changed option come.
Please help.

**Comment by nikitakapoor1919** [comment]
@Namanl2001 sir i am facing some issues in resolving merge conflicts as I delete the readme file. Can I make new pull request as in my locals I am unable to push any file. 
please help.

**Comment by Namanl2001** [comment]
don't panic @nikitakapoor1919 you could read about 'rebasing' from the contributions.md file present in the root. It might need you to solve some merge conflicts but then you will be able to push your commits in this branch/pr.
It's not a good practice to delete a pr/branch until its very difficult to resolve the conflicts.
Really appreciate your efforts. Thanks!

**Comment by nikitakapoor1919** [comment]
@Namanl2001  Have a look !

**Comment by Namanl2001** [comment]
Looks good but could we increase the retention time along adding some animation to it?

**Comment by nikitakapoor1919** [comment]
Okay I will do that .

**Comment by nikitakapoor1919** [comment]
@Namanl2001 I am facing some issues pushing in this branch may be because I have forced push few changes. What can I do ?

**Comment by nikitakapoor1919** [comment]
I have increased timer and added animation ( alert box appears to come from top- bottom)

And conflicts are coming with changes I have pushed.

**Review by Namanl2001 — APPROVED** [review]
LGTM! let's resolve conflicts before merging.

**Comment by nikitakapoor1919** [comment]
@Namanl2001 Please guide how can I resolve these conflits. I have tried many thing but they are not working.

**Comment by Namanl2001** [comment]
you can DM me on discord. will be happy to help. You can find me out from discord project channel in the gssoc server.

**Comment by nikitakapoor1919** [comment]
@Namanl2001 Conflicts are resolved.

**Comment by Namanl2001** [comment]
Thanks!

**Pull request merged**
