### PR TITLE
Add Contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
Reference to issue #16 . Added contributing.md

### CODE REVIEW

**Comment by khareyash05** [comment]
Hi @Namanl2001  have a look at this

**Comment by khareyash05** [comment]
@Namanl2001 
Actually When I saw the the link I found it to really useful and it contained the same content as I have so I decided to copy the same ...

**Comment by khareyash05** [comment]
Used HTML elements instead of `&nbsp;`

**Comment by Namanl2001** [comment]
@khareyash05 always verify your changes before pushing. For this PR you could use https://stackedit.io/app# to check your changes. Thanks

**Comment by khareyash05** [comment]
Hey @Namanl2001 I did check the same in stackedit.io .. Do i have to make some changes?

**Comment by Namanl2001** [comment]
attach screenshot. As I'm not seeing any proper formatting in my editor.

**Comment by khareyash05** [comment]
@Namanl2001  I found some small bugs just give me a minute

**Comment by Namanl2001** [comment]
PHAL!

**Comment by khareyash05** [comment]
Thanx @Namanl2001 for those changes. Is there anything I can help you with on this issue?

**Comment by khareyash05** [comment]
Thanx @Namanl2001 for this! I hope I didn't irritate you much!!

**Pull request merged**
