### PR TITLE
rate limiting added

### PR DESCRIPTION
**Pull request by abhudaym**
## Related Issue 

Rate limiting needed to be added.

Closes: #7 

### Describe the changes you've made

Added a package `express-rate-limit` and used it in `backend/routes/users.js`.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] I have verified/tested my code by running it locally.

### CODE REVIEW

**Comment by Namanl2001** [comment]
LGTM! but curious to know about your verification, if you have done any.

**Comment by abhudaym** [comment]
> LGTM! but curious to know about your verification, if you have done any.

I haven't honestly. I thought about it but nothing seem to come to mind to test the limiter. So, as a last resort, I asked you on Issue discussion

**Comment by Namanl2001** [comment]
I also don't know about its testing tbh. Do some research on it. Also keep in mind you are not restricted to use `limiter` you could also use something easy and cool instead of `limiter`. Some mentor can also help you in this. 
cc: @guptaji6489

**Comment by abhudaym** [comment]
[https://stackoverflow.com/questions/63160152/mocking-express-rate-limit-for-unit-testing](url)
Found this but failed to understand what happened here. Are we looking for something like this?

**Comment by Namanl2001** [comment]
> 
> 
> [https://stackoverflow.com/questions/63160152/mocking-express-rate-limit-for-unit-testing](url)
> Found this but failed to understand what happened here. Are we looking for something like this?

Yes. If facing any problem, you can discuss it on the discord project channel.

**Comment by Namanl2001** [comment]
Already added by someone else thanks for your interest @abhudaym

**Comment by abhudaym** [comment]
How was rate limiting tested?

**Pull request closed without merging**
