### PR TITLE
Updating Backend README.md

### PR DESCRIPTION
**Pull request by Navya-amarneni**
The previous README.md looked very unclean and unorganized. I have updated the Back end README file and added few features to it. It looks very professional and polished compared to the previous README file.

PREVIOUS:

image

MODIFIED:
image

### CODE REVIEW

**Comment by Navya-amarneni** [comment]
@Namanl2001 @nikitakapoor1919 Kindly look at my PR and assign this issue to me as part of GSSOC'21. Please suggest any changes required.

**Comment by Namanl2001** [comment]
thanks @Navya-amarneni all the required details are now updated in the main readme file so for this pr you can directly delete this backen/readme

**Comment by Navya-amarneni** [comment]
@Namanl2001  File is deleted .Kindly have a look at PR

**Review by Namanl2001 — APPROVED** [review]
Thanks!

**Pull request merged**
