### PR TITLE
navbar updated

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue 

- Navbar is updated 
Closes: #35 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Enhancement in the existing features
- [ x] Other

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x ] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly whereever it was hard to understand.
- [ x] My changes generate no new warnings.
- [ x] I have verified/tested my code by running it locally.

## Additional Info (optional)
Any additional information you want to give

Gurujii com - Google Chrome 05-05-2021 18_51_11
Gurujii com - Google Chrome 05-05-2021 18_51_17

### CODE REVIEW

**Comment by Ankita297** [comment]
@Namanl2001 @sagar-barapatre Please review my PR .

**Comment by Namanl2001** [comment]
Looks good but can we make something more cool and attractive. WDYT? @Ankita297

**Comment by Ankita297** [comment]
Add the logo maybe @Namanl2001 ?

**Comment by Ankita297** [comment]
or any suggestions from your side .

**Comment by Namanl2001** [comment]
I don't have any hard suggestions. Maybe we can search it on the internet for some awesome and attractive navbars.
@sagar-barapatre can also help us with this.

**Comment by sagar-barapatre** [comment]
Actually we don't have multiple pages for this website. So once we get it done we can even improve the navbar. Until then acc to me, this looks fine.

**Comment by Ankita297** [comment]
okay @Namanl2001 @sagar-barapatre .

**Pull request merged**
