### PR TITLE
Added various security features issue #76

### PR DESCRIPTION
**Pull request by udaymittal7**
Added helmet for security http headers.
Added rate limiter to receive 100 requests per hour from a particular IP address.
Added mongo sanitize for data sanitization against noSQL query injection
Added xss for data sanitization against XSS.

Please review and if any changes required let me know.
Thank you.

For issue #76

### CODE REVIEW

**Comment by Namanl2001** [comment]
How have you tested these?

**Comment by udaymittal7** [comment]
Tested the rate limiter and mongo sanitize. 
Helmet is adding the required headers too.

**Comment by Namanl2001** [comment]
that's what i'm asking. HOW?
can you add some tests for these security features?

**Comment by udaymittal7** [comment]
I can't test for 100 request per hour so I changed it to 2 and tested. It was working.
Helmet is adding necessary headers in each request.
I checked them by making requests in postman.

I don't know how to add tests. Please tell me how and then I will.

**Comment by Namanl2001** [comment]
> 
> 
> I can't test for 100 request per hour so I changed it to 2 and tested. It was working.
> Helmet is adding necessary headers in each request.
> I checked them by making requests in postman.

Great! But adding test cases makes the code strong and also saves time for future contributors like if they do some change then they might have to do all the testing manually each time.

>I don't know how to add tests. Please tell me how and then I will.

I also don't know how to test this feature but would let you know if I find something interesting till then you could also do some research on it or can also discuss your problems with the mentors in the project discord channel.

**Comment by udaymittal7** [comment]
If you are asking how to test this feature, here goes.
For helmet, just make any request using postman and see if the necessary http headers are included which were not there when helmet was not used.
For rate limiter, change the max requests to '2' and try making more than 2 requests from the same IP, it will throw an error.
For mongo sanitize, try passing { $gt : "" } in username while signing in and pass in any of the correct passwords and it will login.
For xss attack, try sending a script tag which includes listening to various events like 'click'. Hackers can use this to gain access to our database.

**Comment by Namanl2001** [comment]
I'm asking for some e2e/unit tests. if possible.

**Comment by Namanl2001** [comment]
If not comfortable with testing, we can leave it for the future work.

**Comment by udaymittal7** [comment]
I read your article but I haven't implemented testing nor e2e/ unit tests before. I don't know how to integrate that with this app.

**Review by Namanl2001 — APPROVED** [review]
Great work! Thanks

**Pull request merged**
