### PR TITLE
Removed body-parser

### PR DESCRIPTION
**Pull request by Muditxofficial**
## Related Issue 

- Info about the related issue 

Closes: #144 

### Describe the changes you've made

Removed deprecated code

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [x] Other

## Mention any unusual behaviour of your code (Write NA if not)
No

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

### CODE REVIEW

**Comment by Namanl2001** [comment]
update readme.md accordingly. where line numbers are written to be commented out. Thanks

**Comment by Muditxofficial** [comment]
> update readme.md accordingly. where line numbers are written to be commented out. Thanks

 do i need to give more details about which line to comment ?

**Comment by Namanl2001** [comment]
no more details just change the line numbers according to your code change sin server.js

**Review by Namanl2001 — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
