### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by akshay1027**
## Related Issue 
updated the lines that has to commented to not use the database at all.

Closes: #114

### CODE REVIEW

**Review by sagar-barapatre — APPROVED** [review]

**Review by sagar-barapatre — CHANGES_REQUESTED** [review]
lines 5,7,20, 23 should also be included in that...don't remove that line

**Comment by akshay1027** [comment]
requested changes have been made @sagar-barapatre

**Review by sagar-barapatre — APPROVED** [review]

**Comment by Namanl2001** [comment]
AFAIK correct lines to be commented should be `10` and `43`

**Comment by akshay1027** [comment]
Shall I change them then? @Namanl2001

**Comment by Namanl2001** [comment]
Yeah, sure

**Comment by akshay1027** [comment]
changes done @Namanl2001

**Pull request merged**
