### PR TITLE
Header is fixed

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue 

Navbar is fixed at top as when  you scroll down it will remain intact .

Closes: #31 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Enhancement in the existing features
- [ x] Other

## Mention any unusual behaviour of your code (Write NA if not)
NA
## Checklist:

- [x ] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [ x] My changes generate no new warnings.
- [ x] I have verified/tested my code by running it locally.

## Additional Info (optional)
Any additional information you want to give

https://user-images.githubusercontent.com/67833077/116518245-a1c9bb00-a8ed-11eb-91b3-946d947e34ae.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@Namanl2001 @sagar-barapatre Please review my PR .

**Review by sagar-barapatre — APPROVED** [review]
Okay this was easy.

**Comment by Ankita297** [comment]
@Namanl2001 is this okay ?

**Review by Namanl2001 — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
