### PR TITLE
Added home/external tutor filter

### PR DESCRIPTION
**Pull request by tend2infinity**
Closes: #111

### Describe the changes you've made
I have just added a new 'tutor' state in the reducer and I am manipulating it in accordance with other filters as required.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

## Additional Info (optional)
Please tag @akshay1027 along with me in this PR

### CODE REVIEW

**Comment by Namanl2001** [comment]
Great work! Just a small issue. To reproduce follow below steps:

- apply filters -> external, maths, 9th
- search for some pincode, then all filters will be set to `ALL` (as required)
- but if search for some tutor name then external tutor doesn't changes to `ALL` but other two filter does.

I hope I'm a bit clear if not feel free to ask.

**Comment by Namanl2001** [comment]
@akshay1027

**Comment by tend2infinity** [comment]
> Great work! Just a small issue. To reproduce follow below steps:
> 
> * apply filters -> external, maths, 9th
> * search for some pincode, then all filters will be set to `ALL` (as required)
> * but if search for some tutor name then external tutor doesn't changes to `ALL` but other two filter does.
> 
> I hope I'm a bit clear if not feel free to ask.

See imo the name filter should be separated from other filters as right now the name filter matches with only one teacher. So, other filters seem irrelevant . I can modify the logic of this name filter as right now it is based on "if the name we type is absolutely equal to a teacher's name in our db" but technically it should be like "it a teacher's name string includes a particular substring which we type". I feel I can put another issue for that!

**Comment by tend2infinity** [comment]
Meanwhile, I have resolved that earlier issue

**Comment by Namanl2001** [comment]
> "if a teacher's name string includes a particular substring which we type" it should show us the related queries. I feel I can put another issue for that!

Please go ahead and thanks for this great work!

**Comment by akshay1027** [comment]
> @akshay1027 I am unable to assign you this. Better comment something on this PR. So that I can see a option to assign you. Thanks

sure!

**Comment by akshay1027** [comment]
Hey @Namanl2001, I have not got the marks as you have already merged it

**Comment by akshay1027** [comment]
I have removed comments and made PR, you can give level 2 label in that and merge it

**Pull request merged**
