### PR TITLE
Double Form Added

### PR DESCRIPTION
**Pull request by AakankshaShah**
## Double column form #8
- At present we have a single-column form for creating and editing users' profiles but it is quite small to contain all the input fields uniformly.

Closes: #[8]

### Describe the changes you've made

Created a double form column for creating & updating profile.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

## Additional Info (optional)
image
image

### CODE REVIEW

**Comment by Namanl2001** [comment]
I guess you have used npm install. Instead, use `yarn install` as instructed in readme.md and then after verifying your changes, push them again.

**Comment by AakankshaShah** [comment]
Sir I checked everything using yarn ,it's completely working fine.

**Comment by Namanl2001** [comment]
🤔 But why there are so much of deletions? Do you have any idea about it? Mainly the json files

**Comment by AakankshaShah** [comment]
Sir ,I have cleared package-lock files -it won't be an issue ,that's  why there are so many deletions.

**Comment by Namanl2001** [comment]
Deleting lock.json files is not a good practice and can cause problems to other developers on this project you can refer [here](https://stackoverflow.com/questions/44297803/what-is-the-role-of-the-package-lock-json). Would suggest reverting those changes.

**Review by Namanl2001 — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
