### PR TITLE
Readme Ui updated ,Technology Stack Added

### PR DESCRIPTION
**Pull request by nikitakapoor1919**
### Improve README.md #17

Added Technology Stack,update UI of README.md

### CODE REVIEW

**Comment by Namanl2001** [comment]
You have made 15k lines of change 😅. May be you have used npm install, instead use yarn install after deleting package-lock.json from frontend as well as backend.

**Comment by nikitakapoor1919** [comment]
Yes i have use npm install . I didn't know about this. What should i do now?

**Comment by nikitakapoor1919** [comment]
@Namanl2001 So I need to make new pull request with these changes?

**Comment by Namanl2001** [comment]
No need to delete, push your changes in this pr only. It should work.

**Pull request closed without merging**
