### PR TITLE
controller module created for handling endpoints (#82)

### PR DESCRIPTION
**Pull request by singhayushh**
## Related Issue 
Using industry standards for backend project structuring - using separate controllers directory to manage endpoint requests.
Closes: #82 

### Describe the changes you've made
The existing structure of the code was the handler functions for each routes were coded right inside the router definition. I have now moved all handler functions to a separate directory named 'controllers'. Now each of the route just has a function call to the respective handler. This is an industry standard convention that helps in better code maintenance, readability as well as debugging.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [x] Other

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

### CODE REVIEW

**Review by Namanl2001 — APPROVED** [review]
LGTM! Thanks

**Comment by singhayushh** [comment]
Hey can this PR be merged anytime soon? 
I am about to start with another issue

**Comment by Namanl2001** [comment]
Should this be closed ?

**Comment by singhayushh** [comment]
> Should this be closed ?

This should have been automatically merged. Idk what happened
I see the code updated in the main repository .

**Pull request closed without merging**
