### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by Vaibhav-afk**
## Related to Issue #57 

- Added favicon

### CODE REVIEW

**Comment by Vaibhav-afk** [comment]
I've added favicon in `png` extension , If you want I can add favicon in `icon` extension. However `png` will work fine.

**Comment by Namanl2001** [comment]
It's good but in the browser just looking like a blue dot. Can you come up with any other visible favicon? I guess "G" will look nice or any other of your choice. Thanks

**Comment by Vaibhav-afk** [comment]
I have updated favicon.

**Comment by Namanl2001** [comment]
Thanks

**Pull request merged**
